apiVersion: v1
kind: Service
metadata:
  name: import-cfs-process
  namespace: dtag-dev
  labels:
    app: import-cfs-process
    version: latest
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 18926
    nodePort: 30926
    targetPort: 9026
    protocol: TCP
  selector:
    app: import-cfs-process
    version: latest